### ISSUE TITLE
Create application table

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#1]
Create application table
Define CRUD API calls in swagger.yml
Implement API call in python

Table definition
-	Name
-	SolutionID #solution the application belongs to
-	Description
-	ActivatorID #link to the activator that creates the application
-	Deployed #true/false

**Comment by karwootang-gft** [comment]
This is an example json message, we have activatorId and the solutionId and status fields to whether deployed or not: 

 {
    "activatorId": 1,
    "description": "\n    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eius",
    "env": "DEV",
    "id": 1,
    "name": "Placeholder",
    "solutionId": 1,
    "status": "Active"
  }
