### ISSUE TITLE
Move Resources column from Activator to Application table

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#102]
@Salles-FA 

Other columns?

**Comment by karwootang-gft** [comment]
Landing Zone builds come from the DaC

**Comment by Salles-FA** [comment]
Hi @karwootang-gft,

Only 'resources' column must move now, yes.

Thank you in advance,
Fábio

**Comment by karwootang-gft** [comment]
Hi @Salles-FA - this is done, new experimental image available for the Houston Service and mysql57

**Comment by andy12838729** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/80

**Comment by andy12838729** [comment]
Please note - the Activator does have resrouces - its the TF Plan from the docker image. But those are the resources it **_will_** DEPLOY. The Application has the actual resources _**actually**_ DEPLOYED.
