### ISSUE TITLE
Add solutiondeployment endpoint

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#112]
1. Eagle Console to supply the "solution id" in the json payload to the Houston Service
2. Houston Service will send the complete solution as a json payload to the DaC
  - How do we decide which DaC to send the message to?
3. DaC will respond when complete back to the Houston Service to update the Solution using the new Houston Service Solutiondeployment Endpoint

**Comment by karwootang-gft** [comment]
@sunderhill-gft

**Comment by karwootang-gft** [comment]
@sunderhill-gft Hi Simon, This is a sample of the solution json you should expect: 
https://raw.githubusercontent.com/tranquilitybase-io/tb-houston-service/master/docs/solution_response_1587029263652.json
Thanks

**Comment by Salles-FA** [comment]
> @andy12838729 @Salles-FA @sunderhill-gft, is the Activator.platforms field is used to decide which DaC to send the request to? Is this field on the right object, I have a feeling it should be on the Application object?

- Activator.platforms (e.g. ["Azure", "GCP", "AWS", "Other", "Fancy"]) -- is an information related to the valid cloud environments this specific activator was tested for deploy a new Application on.
- Solutions will be multi-cloud. 

So @sunderhill-gft  the DaC should read this field to see if this Activator is valid for current env. For example: DaC-GCP will reject an Activator.platforms ["Azure", "AWS"]. 

Is that correct @andy12838729 ?

Regards,
Fábio

**Comment by Salles-FA** [comment]
Hi @karwootang-gft,

As discussed before, the UI will POST the Solution's ID.
- For example: Body: {id: 1}

The UI will keep polling the GET REST method and the API response should resemble the following:
```
[
  {
    id: 1,
    deployed: true
  }
  {
    id: 2,
    deployed: true
  }
  {
    id: 3,
    deployed: false
  }
   ...
]
```

**Comment by karwootang-gft** [comment]
> > @andy12838729 @Salles-FA @sunderhill-gft, is the Activator.platforms field is used to decide which DaC to send the request to? Is this field on the right object, I have a feeling it should be on the Application object?
> 
> * Activator.platforms (e.g. ["Azure", "GCP", "AWS", "Other", "Fancy"]) -- is an information related to the valid cloud environments this specific activator was tested for deploy a new Application on.
> * Solutions will be multi-cloud.
> 
> So @sunderhill-gft the DaC should read this field to see if this Activator is valid for current env. For example: DaC-GCP will reject an Activator.platforms ["Azure", "AWS"].
> 
> Is that correct @andy12838729 ?
> 
> Regards,
> Fábio

Activator.Platforms makes sense as the list of supported Cloud providers. 

But, my actual question is there a Master DaC the Houston Service interacts with?
Or is the plan the Houston Service interacts with all DaCs? 

How do we know which Cloud to deploy the Solution to? To me Multi-Cloud means that we support many Clouds but it doesn't mean we deploy the solution to all Clouds.

**Comment by karwootang-gft** [comment]
> Hi @karwootang-gft,
> 
> As discussed before, the UI will POST the Solution's ID.
> 
> * For example: Body: {id: 1}
> 
> The UI will keep polling the GET REST method and the API response should resemble the following:
> 
> ```
> [
>   {
>     id: 1,
>     deployed: true
>   }
>   {
>     id: 2,
>     deployed: true
>   }
>   {
>     id: 3,
>     deployed: false
>   }
>    ...
> ]
> ```

Sure, we can create a new table for this:
solutiondeployment
id int
solution_id int
deployed boolean
last_updated string 

And add the endpoints:
solutiondeployment POST(id) # Post a single solution deployment
solutiondeployments GET # Return a list of solution deployments 
solutiondeployment GET(id) # Get a single solution deployment
solutiondeployment PUT(id) # Update an existing solution deployment 
solutiondeployment DELETE(id) # Delete a solution deployment

**Comment by Salles-FA** [comment]
> > Hi @karwootang-gft,
> > As discussed before, the UI will POST the Solution's ID.
> > 
> > * For example: Body: {id: 1}
> > 
> > The UI will keep polling the GET REST method and the API response should resemble the following:
> > ```
> > [
> >   {
> >     id: 1,
> >     deployed: true
> >   }
> >   {
> >     id: 2,
> >     deployed: true
> >   }
> >   {
> >     id: 3,
> >     deployed: false
> >   }
> >    ...
> > ]
> > ```
> 
> Sure, we can create a new table for this:
> solutiondeployment
> id int
> solution_id int
> deployed boolean
> last_updated string
> 
> And add the endpoints:
> solutiondeployment POST(id) # Post a single solution deployment
> solutiondeployments GET # Return a list of solution deployments
> solutiondeployment GET(id) # Get a single solution deployment
> solutiondeployment PUT(id) # Update an existing solution deployment
> solutiondeployment DELETE(id) # Delete a solution deployment

Hi @karwootang-gft, 

It can use the same "Solution" table with a new Boolean column 'deployed'. This EndPoint will query only this two fields.

Thanks,
Fábio

**Comment by karwootang-gft** [comment]
> > > Hi @karwootang-gft,
> > > As discussed before, the UI will POST the Solution's ID.
> > > 
> > > * For example: Body: {id: 1}
> > > 
> > > The UI will keep polling the GET REST method and the API response should resemble the following:
> > > ```
> > > [
> > >   {
> > >     id: 1,
> > >     deployed: true
> > >   }
> > >   {
> > >     id: 2,
> > >     deployed: true
> > >   }
> > >   {
> > >     id: 3,
> > >     deployed: false
> > >   }
> > >    ...
> > > ]
> > > ```
> > 
> > 
> > Sure, we can create a new table for this:
> > solutiondeployment
> > id int
> > solution_id int
> > deployed boolean
> > last_updated string
> > And add the endpoints:
> > solutiondeployment POST(id) # Post a single solution deployment
> > solutiondeployments GET # Return a list of solution deployments
> > solutiondeployment GET(id) # Get a single solution deployment
> > solutiondeployment PUT(id) # Update an existing solution deployment
> > solutiondeployment DELETE(id) # Delete a solution deployment
> 
> Hi @karwootang-gft,
> 
> It can use the same "Solution" table with a new Boolean column 'deployed'. This EndPoint will query only this two fields.
> 
> Thanks,
> Fábio

Works for me, thanks.

**Comment by karwootang-gft** [comment]
@Salles-FA, The feature/solution-deploy branch is failing, it calling the wrong endpoint.

:4200/api/solutiondeploy/:1

Should be using: 
/api/solutiondeployment POST(id)

Is the UI using teh /api/solutiondeployments endpoint yet, how does it get called?

I pushed out a new experimental image with the above changes.
if you don't like the endpoint name I can change that next week.

**Comment by Salles-FA** [comment]
Hi Karwoo,

I've just updated it. 

Thanks,
Fábio

https://github.com/tranquilitybase-io/tb-eagle-console/commit/ab4c6b35f07874a3b7538106d4fe5b641a511f9b

**Comment by karwootang-gft** [comment]
> Hi @karwootang-gft,
> 
> As discussed before, the UI will POST the Solution's ID.
> 
> * For example: Body: {id: 1}
> 
> The UI will keep polling the GET REST method and the API response should resemble the following:
> 
> ```
> [
>   {
>     id: 1,
>     deployed: true
>   }
>   {
>     id: 2,
>     deployed: true
>   }
>   {
>     id: 3,
>     deployed: false
>   }
>    ...
> ]
> ```

Hi @Salles-FA, This endpoint is done and available in the latest experimental image:
https://tranquilitybase-io.github.io/tb-houston-service/#operation/solution.deployment_read_all

thanks,
Karwoo

**Comment by karwootang-gft** [comment]
> @Salles-FA, The feature/solution-deploy branch is failing, it calling the wrong endpoint.
> 
> :4200/api/solutiondeploy/:1
> 
> Should be using:
> /api/solutiondeployment POST(id)
> 
> Is the UI using teh /api/solutiondeployments endpoint yet, how does it get called?
> 
> I pushed out a new experimental image with the above changes.
> if you don't like the endpoint name I can change that next week.

Hi @Salles-FA,

I fixed in the call in the eagle-console, in the feature/solution-deploy branch. 

Endpoint doc is here:
https://tranquilitybase-io.github.io/tb-houston-service/index.html#operation/solution.deployment_create

Thanks,
Karwoo

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14
https://github.com/tranquilitybase-io/TranquilityBase/issues/15
