### ISSUE TITLE
Add solution put operation

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#113]
@Salles-FA 
I just noticed this was missing, and was needed as it was discussed on the call yesterday.
The server side code is there, it's just missing from the openapi.yml file.

Just needs added and tested.

**Comment by Salles-FA** [comment]
Hi,

Ok, @kwicherska also noticed that. :)

Once you have it, please make a new 'experimental' image for us to test and implement the feature https://github.com/tranquilitybase-io/tb-eagle-console/issues/54

Thank you,
Fábio

**Comment by karwootang-gft** [comment]
I will do that today thanks.

**Comment by karwootang-gft** [comment]
It makes sense to me that I do this after moving the resource column to Application or at the same time.

**Comment by karwootang-gft** [comment]
Hi @Salles-FA @kwicherska  - this is done, new experimental image available for the Houston Service and mysql57

**Comment by Salles-FA** [comment]
Hi @karwootang-gft,

Thank you, we are testing it now. I'll let you know ASAP, then we can close this issue.

**Comment by karwootang-gft** [comment]
fyi - link to the doc: https://tranquilitybase-io.github.io/tb-houston-service/index.html#operation/solution.deployment_update
