### ISSUE TITLE
Send the folder/project structure to the DaC

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#114]
@Salles-FA - How will you be sending the folder/project structure to the Houston Service?

**Comment by Salles-FA** [comment]
It is created during the "Create New Solution" process.

The UI will POST the solutionId so you can get all stored solutions' info from DB.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/16
https://github.com/tranquilitybase-io/TranquilityBase/issues/18
https://github.com/tranquilitybase-io/TranquilityBase/issues/24

**Comment by karwootang-gft** [comment]
- The folder structure is hierarchical, so probably best if it's sent (by the Eagle Console) as a json string (to the Houston Service) and stored (as a json string in the DB as a TEXT field), which is then passed to the DAC as part of the solution deployment. 
- Depending only how complex the folder structure is we can store in the solution table or in it's own table with foreign key to solution

**Comment by karwootang-gft** [comment]
e.g. 

{
  "folder1": [
       "folder3": ['folder7'], 
       "folder5"
   ],
  "folder2":  ["folder4", "folder6"],
  "folder8"
}

**Comment by karwootang-gft** [comment]
@Salles-FA @sunderhill-gft 

Create new rest endpoint (HS + DAC) for creating folder structure needs to be executed before any solutions are deployed.

**Comment by Salles-FA** [comment]
Hi @karwootang-gft,

What about this?

- Example1:
```json
[
  {
    "id": 1,
    "name": "application x",
    "type": "Applications",
    "gcpType": "Folder",
    "children": [
      {
        "id": 1,
        "name": "solution x",
        "type": "Solutions",
        "gcpType": "Folder",
        "children": [
          { "name": "workspace", "type": "Workspaces", "gcpType": "Project" },
          { "name": "dev", "type": "Environments", "gcpType": "Project" },
          { "name": "staging", "type": "Environments", "gcpType": "Project" },
          { "name": "prod", "type": "Environments", "gcpType": "Project" }
        ]
      },
      {
        "id": 2,
        "name": "solution xx",
        "type": "Solutions",
        "gcpType": "Folder",
        "children": [
          { "name": "workspace", "type": "Workspaces", "gcpType": "Project" },
          { "name": "dev", "type": "Environments", "gcpType": "Project" },
          { "name": "staging", "type": "Environments", "gcpType": "Project" },
          { "name": "prod", "type": "Environments", "gcpType": "Project" }
        ]
      }
    ]
  }
]
```

**Comment by karwootang-gft** [comment]
there a limit to the levels the folders can be nested: https://cloud.google.com/resource-manager/docs/creating-managing-folders. It's currently 10.

**Comment by karwootang-gft** [comment]
Hi Fabio, what about the business unit and teams folders?
Also, folders between Applications <-> solutions need to be created before the solutions are created. Aren't solutions created one at a time, this json suggests all the folders for all solutions are created at the same time.

**Comment by sunderhill-gft** [comment]
the folder structure only needs to be defined once and should be created separately to the solution deployment. it defines the layers between the top level 'applications' folder and the solution folders that get created when deploying solutions.

**Comment by karwootang-gft** [comment]
Hi Simon @sunderhill-gft, I think this is what we discussed. Would this work for you Fabio @Salles-FA?

We're proposing we create folders and retrieve and store folder ids (in the db).

e.g.
EC + HS send a list of folders to create to DAC.
[
"business unit a",
"business unit b"
]

DAC sends back the list with corresponding folder ids, plus the folderId for root.
{
“root”: “folderId1”,
"business unit a”: “folderId1”,
"business unit b”: “folderId2”
}


When deploying solutions, the json must contain the folder id.

{
“Id”: 1,
“folderId”: “folderId1”
}

The DAC will then create the solution in the appropriate folder.

e.g.

"business unit a/solution x/workspace”,
"business unit a/solution x/dev”,
"business unit a/solution x/staging”,
"business unit a/solution x/prod”

Do we need the root Application X folder as that could be implied?

**Comment by sunderhill-gft** [comment]
Hi this is not quite we agreed on.
We agreed this. 
HS sends key value pairs representing the folder structure in parent/child key/value pairs
e.g.
{
    "applications": "business unit a",
    "applications": "business unit b",
    "business unit a": "team a",
    "business unit a": "team b",
    "business unit b": "team c",
    "business unit b": "team c"
}

DAC creates this folder structure and returns the folder id for each folder created
e.g.
{
    "business unit a": "837648326"
    "business unit b": "898648326"
    "team a": "862734326"
    "team b": "243289326"
}

**Comment by Salles-FA** [comment]
> Hi Fabio @Salles-FA, what about the business unit and teams folders?

This is to be configured at this screen:
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/71

**Comment by karwootang-gft** [comment]
> Hi this is what we agreed on.
> HS sends key value pairs representing the folder structure in parent/child key/value pairs
> e.g.
> {
> "applications": "business unit a",
> "applications": "business unit b",
> "business unit a": "team a",
> "business unit a": "team b",
> "business unit b": "team c",
> "business unit b": "team d"
> }
> Can use applications or root for top level folder. DAC already has the folder id for the top level folder from LZ config but useful to specify in project structure tree
> 
> The rest is ok I think. Solution in this case could only be deployed in one of the bottom level team folders.

Hi Simon, This is valid json but the keys are not unique, which will make it slightly more difficult to generate. Can you accept a list of key value pairs instead? 
![Uploading Screenshot 2020-05-15 at 09.20.14.png…]()

**Comment by sunderhill-gft** [comment]
Hi Karwoo, a list is totally fine.

**Comment by karwootang-gft** [comment]
> Hi Karwoo, a list is totally fine.

How are the folder id's returned in the GET operation?

Here's an idea I have:

    [
        "folderId1": [
            "application x",
            "solution x"
        ],
        "folderId2": [
            "solution x",
            "workspace"
        ],
        "folderId3": [
            "solution x",
            "dev"
        ],
        "folderId4": [
            "solution x",
            "staging"
        ]
]

**Comment by sunderhill-gft** [comment]
There would be no solutions involved at all when creating the initial folder structure
so using the example I posted above return
[
  [
   folderName: "business unit a",
   folderId: 163288,
   anyOtherSetting: xxxx
 ],
 [
   folderName: "business unit b",
   folderId: 761383
 ],
 [
   folderName: "team a",
   folderId: 683763
 ],
 [
   folderName: "team b",
   folderId: 655763
 ],
 [
   folderName: "team c",
   folderId: 773763
 ],
 [
   folderName: "team d",
   folderId: 113722
 ]
]

so matching the passed folder names with their folder ids and adding any other folder settings that  might be added later.

**Comment by karwootang-gft** [comment]
> There would be no solutions involved at all when creating the initial folder structure
> so using the example I posted above return
> [
> [
> folderName: "business unit a",
> folderId: 163288,
> anyOtherSetting: xxxx
> ],
> [
> folderName: "business unit b",
> folderId: 761383
> ],
> [
> folderName: "team a",
> folderId: 683763
> ],
> [
> folderName: "team b",
> folderId: 655763
> ],
> [
> folderName: "team c",
> folderId: 773763
> ],
> [
> folderName: "team d",
> folderId: 113722
> ]
> ]
> 
> so matching the passed folder names with their folder ids and adding any other folder settings that might be added later.

That works for me, with valid json this becomes (anyOtherSettings could be other keys are options):

    [
       {
          "folderName":"business unit a",
          "folderId": 163288,
          "anyOtherSetting":"xxxx"
       },
       {
          "folderName":"business unit b",
          "folderId": 761383,
          "anyOtherSetting":"xxxx"
       },
       {
          "folderName":"team a",
          "folderId": 683763,
          "anyOtherSetting":"xxxx"
       },
       {
          "folderName": "team b",
          "folderId": 655763,
          "anyOtherSetting":"xxxx"
       },
       {
          "folderName":"team c",
          "folderId":773763,
          "anyOtherSetting":"xxxx"
	},
        {
          "folderName":"team d",
          "folderId":113722,
          "anyOtherSetting":"xxxx"
        }
    ]

**Comment by karwootang-gft** [comment]
> Hi @karwootang-gft,
> 
> What about this?
> 
> * Example1:
> 
> ```json
> [
>   {
>     "id": 1,
>     "name": "application x",
>     "type": "Applications",
>     "gcpType": "Folder",
>     "children": [
>       {
>         "id": 1,
>         "name": "solution x",
>         "type": "Solutions",
>         "gcpType": "Folder",
>         "children": [
>           { "name": "workspace", "type": "Workspaces", "gcpType": "Project" },
>           { "name": "dev", "type": "Environments", "gcpType": "Project" },
>           { "name": "staging", "type": "Environments", "gcpType": "Project" },
>           { "name": "prod", "type": "Environments", "gcpType": "Project" }
>         ]
>       },
>       {
>         "id": 2,
>         "name": "solution xx",
>         "type": "Solutions",
>         "gcpType": "Folder",
>         "children": [
>           { "name": "workspace", "type": "Workspaces", "gcpType": "Project" },
>           { "name": "dev", "type": "Environments", "gcpType": "Project" },
>           { "name": "staging", "type": "Environments", "gcpType": "Project" },
>           { "name": "prod", "type": "Environments", "gcpType": "Project" }
>         ]
>       }
>     ]
>   }
> ]
> ```

Hi Fabio, This works for me, cheers, I will add the other examples [here](https://github.com/tranquilitybase-io/tb-houston-service/wiki/Technical-Documentation---Landing-Zone-Folder-Structures).

**Comment by karwootang-gft** [comment]
> There would be no solutions involved at all when creating the initial folder structure
> so using the example I posted above return
> [
> [
> folderName: "business unit a",
> folderId: 163288,
> anyOtherSetting: xxxx
> ],
> [
> folderName: "business unit b",
> folderId: 761383
> ],
> [
> folderName: "team a",
> folderId: 683763
> ],
> [
> folderName: "team b",
> folderId: 655763
> ],
> [
> folderName: "team c",
> folderId: 773763
> ],
> [
> folderName: "team d",
> folderId: 113722
> ]
> ]
> 
> so matching the passed folder names with their folder ids and adding any other folder settings that might be added later.

Hi Simon,
For the scenario where solutions placed in the root folder e.g. application X, we would still need to send a request to the DAC, and get a folder Id back, can you confirm what needs to be sent?

**Comment by sunderhill-gft** [comment]
Linking with [DAC issue 67](https://github.com/tranquilitybase-io/tb-gcp-dac/issues/67)

**Comment by karwootang-gft** [comment]
As part of the solution deployment we also need to send the deploymentFolderId.

1. Create folders one at a time
2. To create a file we call /folder_async/ endpoint the parentFolderId and folderName as parameters.
3. Once all folders are created, send the solution deployment with the leaf folder id as the deploymentFolderId.
