### ISSUE TITLE
Add Integration semantic versioning

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#117]
Version and tag each repo with a shared semantic version.

This is done manually when appropriate, for example after system integration testing is successful.

The version number is more elaborate than the standard <major>.<minor>.<patch> number.

e.g . 

- optional pre-release number
- optional build number 

This tool may be better for generating and maintaining this number.
https://github.com/fsaintjacques/semver-tool

Once this task is done, we'll need a tool to help remove and add tags across our repos as new releases become available.

**Comment by Salles-FA** [comment]
Hi @karwootang-gft,

I'm closing this issue because this feature will be implemented in another repository.

**Comment by karwootang-gft** [comment]
@Salles-FA - this task should be re-opened, this task spans multiple projects. As we need to create create the tags in each repo. 

On the right hand-side you can add the Projects/repos affected.
