### ISSUE TITLE
List of distinct Activator categories

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#12]
List of distinct Activator categories

**Comment by karwootang-gft** [comment]
@Salles-FA - Can we get this information from the full list of Activators, or do we want a new endpoint created just for this purpose?

**Comment by karwootang-gft** [comment]
/api/activatorcategories

**Comment by karwootang-gft** [comment]
See "Retrieve list of Activators #8"

Need to add source column and sourceControlURL column. 

Hi - they are different. SourceControl would be the system like git or if on GCP - Cloud Source Repositories that the Activator can be deployed to. (Configured in EC).

There also needs to be a link to the actual code for the activator.
