### ISSUE TITLE
Houston changes to support solution deployment 

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#136]
WIP

**Is your feature request related to a problem? Please describe.**
Houston changes to support Solution deployments

**Describe the solution you'd like**
Create a new table solutionresource
columns:
id: int (auto increment)
solutionId: int 
key: string
value: string

Solution new columns:
error_id: int 
error_code: string
error_message: string 
Solution.deploymentState string 

Rest API changes:
When the Eagle Console queries for the solution deployments, return all solutions, deployed and deploymentState fields. Houston Service will query DaC if the solution deployment is still in progress and perform appropriate updates to the database. 

Endpoint changes
https://tranquilitybase-io.github.io/tb-houston-service/api/solution(s)
Addition of the deplomentState field and error fields 
TBD - additional fields 

**Describe alternatives you've considered**
TBD

**Additional context**

Whoever designed the activator (the activator designed) decides the folder structure and every thing within the activator, will some parameters from the user (activator user). I don't think the folder structure should be configurable by the user (activator user). 

Support new interaction with DaC create infra with TF:
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/8

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/15
https://github.com/tranquilitybase-io/TranquilityBase/issues/19
