### ISSUE TITLE
[Feature] Store and parse Terraform State 

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#166]
**Is your feature request related to a problem? Please describe.**
Storing and parsing the Terraform state json file from the DAC. 

**Describe the solution you'd like**
1. Create a new endpoint to receive TF state JSON from the DAC.
2. Create a new table called solutionresourcejson, consisting of 3 columns id (int), solutionId (int) and json (TEXT(30000)). 
3. The endpoint will store the JSON, loop through the JSON, storing important fields into the solutionresource table, for now we just want the projectId.

**Describe alternatives you've considered**
The DAC could just send the key value pairs, but HS has the advantage that we store the whole JSON, and we can extract extra data if needed. 

**Additional context**
None

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/19
