### ISSUE TITLE
[Feature] Add group email address to Team

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-houston-service#171]
**Is your feature request related to a problem? Please describe.**
GCP requires a group email for Project Owner.

![image](https://user-images.githubusercontent.com/53095823/80990992-3e6a9180-8e2f-11ea-9961-136d342adbf3.png)
![image](https://user-images.githubusercontent.com/53095823/80991056-59d59c80-8e2f-11ea-8884-b6dc1b8cc3f6.png)

**Describe the solution you'd like**
Add a new column to the Team to enable a user to enter a group email (SMTP) address that can be passed to the DaC to use to create projects.

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/17
https://github.com/tranquilitybase-io/TranquilityBase/issues/20
https://github.com/tranquilitybase-io/TranquilityBase/issues/23
