### ISSUE TITLE
[Feature] Team/user information needs to be sent to the DaC

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#187]
**Is your feature request related to a problem? Please describe.**
Team/user information needs to be sent to the DAC.

**Describe the solution you'd like**
Send team/user information along with the solution deployment.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/23

**Comment by karwootang-gft** [comment]
Team/TeamMember/Users already send to the DaC as part of the Solution Deployment.
We just need to expand the Role object under TeamMember.
