### ISSUE TITLE
Create solution table

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#2]
Create solution table and CRUD APIs.

Table definition:
-	Name
-	WorkspaceID #link to a defined workspace
-	Business Unit
-	Cost centre
-	Applications[] #list of application ids
-	Teams[] #list of teams that have access to the solution

**Comment by karwootang-gft** [comment]
I think this can be closed, extending this table and endpoints can be done in another task.

**Comment by sunderhill-gft** [comment]
workspaceId will be added during issue #3

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14
