### ISSUE TITLE
Refactoring of Landing Zone metadata end points

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-houston-service#203]
**Is your feature request related to a problem? Please describe.**
Adding more intuitive endpoints to landing zone metadata endpoint group.
Ex: all LAN VPC related metadata needs below end points
/lzmetadata_lan_vpc/{name}
/lzmetadata_lan_vpc/

**Describe the solution you'd like**
Adding above rest end points

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/66
