### ISSUE TITLE
Create model of database

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-houston-service#21]
Create model of database in MySQL Workbench.  
Can use MySql Workbench and reverse engineer from Cloud SQL if [required](
http://grainier.net/connect-google-cloud-sql-with-mysql-workbench/)
Store model in repo

Existing  model is a draw.io diagram [here](https://github.com/tranquilitybase-io/tb-houston-service/blob/master/docs/eagle_houston_backend.drawio)

Export from model for database creation script and check into repo

Includes following tables:
activator
application
businessunit
cd
ci
solution
sourcecontrol
team
user
workspace

and associated join tables e.g. team_user

**Comment by karwootang-gft** [comment]
@sunderhill-gft please find out how workspaces fit into the database model
