### ISSUE TITLE
[BUG] GET "/api/landingzonewan/" is missing "onPremiseSession.primaryPeerIp"

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#216]
**Describe the bug**
On implementing the "Edit" functionality https://github.com/tranquilitybase-io/tb-eagle-console/issues/94 we noticed that it is missing.

**To Reproduce**
1. Create a new WAN VPN connection
2. Go to swagger
3. Click on landingzonewan GET
4. See the error

**Expected behavior**
All data should be returned.

**Additional context**
```json
{
  "googleSession": {
    "primaryGcpVpcSubnet": "DEV",
    "primaryRegion": "DEV",
    "primarySubnetName": "DEV",
    "secondaryGcpVpcSubnet": "",
    "secondaryRegion": "",
    "secondarySubnetName": ""
  },
  "id": 1,
  "onPremiseSession": {
    "primaryBgpPeer": "DEV",
    "primaryPeerIpSubnet": "DEV",
    "primarySharedSecret": "secret",
    "primaryVpnTunnel": "DEV",
    "secondaryBgpPeer": "",
    "secondaryPeerIpSubnet": "",
    "secondarySharedSecret": "",
    "secondaryVpnTunnel": "",
    "vendor": "Fortinet"
  },
  "vpn": {
    "bgpInterfaceNetLength": "DEV",
    "bgpRoutingMode": "Global",
    "cloudRouterName": "DEV",
    "description": "DEV",
    "externalVpnGateway": "DEV",
    "googleASN": 80000,
    "haVpnGateway": "DEV",
    "peerASN": 80001,
    "projectName": "DEV",
    "subnetMode": "Custom",
    "vpcName": "DEV"
  }
}
```

**Comment by Salles-FA** [comment]
Actually: **primaryPeerIp and secondaryPeerIp are missing**

**Comment by karwootang-gft** [comment]
Interestingly secondaryPeerIp is also missing.

**Comment by karwootang-gft** [comment]
This issue appears to be a bug in the python flatten_json module v0.1.7, downgrading to v0.1.6 appears to fix the problem. 

https://github.com/amirziai/flatten/issues/48

**Comment by karwootang-gft** [comment]
This is now what's returned from the get all endpoint:

[
  {
    "googleSession": {
      "primaryGcpVpcSubnet": "string",
      "primaryRegion": "string",
      "primarySubnetName": "string",
      "secondaryGcpVpcSubnet": "string",
      "secondaryRegion": "string",
      "secondarySubnetName": "string"
    },
    "id": 2,
    "onPremiseSession": {
      "primaryBgpPeer": "string",
      "primaryPeerIp": "string",
      "primaryPeerIpSubnet": "string",
      "primarySharedSecret": "string",
      "primaryVpnTunnel": "string",
      "secondaryBgpPeer": "string",
      "secondaryPeerIp": "string",
      "secondaryPeerIpSubnet": "string",
      "secondarySharedSecret": "string",
      "secondaryVpnTunnel": "string",
      "vendor": "string"
    },
    "vpn": {
      "bgpInterfaceNetLength": "string",
      "bgpRoutingMode": "string",
      "cloudRouterName": "string",
      "description": "string",
      "externalVpnGateway": "string",
      "googleASN": 0,
      "haVpnGateway": "string",
      "peerASN": 0,
      "projectName": "string",
      "subnetMode": "string",
      "vpcName": "string"
    }
  }
]
