### ISSUE TITLE
[Feature] Remove Solution.environments column and replace with a SolutionEnvironment table

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#231]
**Is your feature request related to a problem? Please describe.**
solutionenvironment
| id | solutionId | envId | 
| --- | --- | --- |
| 1 | 1 | 1 |
| 2 | 1 | 2 |
| 3 | 2 | 1 |
| 4 | 3 | 2 |

**Describe the solution you'd like**
- Remove the environments columns
- Replace with solutionenvironment rows 

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by Salles-FA** [comment]
Related to this issue: https://github.com/tranquilitybase-io/tb-houston-service/issues/232
