### ISSUE TITLE
[Feature] Standardize separator used in endpoints to dashes "-" as word separator

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#237]
**Is your feature request related to a problem? Please describe.**
There's a mixture of camelcase, no separator, underscore used in the endpoint names.

**Describe the solution you'd like**
Should be standardized, I propose we use hyphen ("-") as the word separator to improve readability of the rest endpoints.

**Describe alternatives you've considered**
Camelcase, no separator, underscore - I think the hyphen looks the best. 

**Additional context**
https://ux.stackexchange.com/questions/41595/what-is-the-casing-convention-for-url-routes

**Comment by Salles-FA** [comment]
@karwootang-gft,

the refereed discussion isn't related to API EndPoints, but for URL patterns for blogs with SEO... etc...

This is not an international convention pattern to everyone follow in APIs.

We've defined in previous discussions to use `camelCase` in our project. If you have a good reason to change we could rethink.
