### ISSUE TITLE
[Feature] LanVPC endpoint refactor

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#241]
**Is your feature request related to a problem? Please describe.**
Combine the 2 endpoints into 1:
/api/lzmetadataLanVpc/
/api/lzmetadataLanVpcEnvironment/

**Describe the solution you'd like**
GET

e.g. /api/lzmetadataLanVpc/
```
[
  {
    "id": 1,
    "isActive": true,
    "name": "Development VPC",
    "environments": [
      {
        "id": 1,
        "isActive": true,
        "name": "Development"
      },
      {
        "id": 2,
        "isActive": true,
        "name": "Production"
      }
    ]
  }
]
```

And with the POST receiving the environments id list, similar to Solutions:
```
[
  {
    "isActive": true,
    "name": "New LAN VPC",
    "environments": [ 1, 3 ]
  }
]
```

**Describe alternatives you've considered**
N/A - As with Solutions, the creation of the LanVPC + Env relationship should be done as a single transaction on the database.

**Additional context**
N/A

**Comment by Salles-FA** [comment]
Related issues:

- tranquilitybase-io/tb-eagle-console#71
- tranquilitybase-io/tb-eagle-console#66
