### ISSUE TITLE
[Feature] Add validation to the /lzEnvironmentDeployment/

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#250]
**Is your feature request related to a problem? Please describe.**
Currently no validation performed in the environment deploy action. 

**Describe the solution you'd like**
"check if all select envs are active"
 "only move from one state to the next when certain conditions are met in the previous step."

**Describe alternatives you've considered**
Validation is good, there is currently no validation.

**Additional context**
N/A

**Comment by Salles-FA** [comment]
@karwootang-gft,

Isn't this already implemented? Please link the PR to this issue.

**Comment by karwootang-gft** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/203
