### ISSUE TITLE
on GET '/api/teammembers/' missing information

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#251]
**Is your feature request related to a problem? Please describe.**
This recently created EndPoint has a relationship with other tables to return expanded objects, information must be displayed in the UI.

**Describe the solution you'd like**
- GET `/api/teammembers/?teamId=1`

**current response body:**
```json
[
  {
    "id": 2,
    "isActive": true,
    "isTeamAdmin": false,
    "roleId": 1,
    "teamId": 1,
    "userId": 1
  }
]
```

**expected response body:**
```json
[
  {
    "id": 2,
    "isActive": true,
    "isTeamAdmin": false,
    "roleId": 1,
    "role": {
        "cloudIdentityGroup": "ecadmins@gftdevgcp.com",
        "description": "eagle console admin role",
        "id": 1,
        "name": "admin"
     },
    "teamId": 1,
    "team": {
        "businessUnit": {
         "description": "Modern Apps",
         "id": 1,
         "isActive": true,
         "name": "Modern Apps"
       },
       "businessUnitId": 1,
       "description": "All Developers",
       "id": 1,
       "isActive": true,
       "lastUpdated": "2020-03-01 12:34:56",
       "name": "Developers",
       "userCount": 1
     },
    "userId": 1,
    "user":   {
        "email": "dev@your.company",
        "firstName": "Jon",
        "id": 1,
        "isActive": true,
        "isAdmin": false,
        "lastName": "Snow",
        "showWelcome": true
      }
  }
]
```

**Describe alternatives you've considered**
N/A

**Additional context**

- https://github.com/tranquilitybase-io/tb-houston-service/pull/248
- https://github.com/tranquilitybase-io/tb-houston-service/issues/236

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-eagle-console/issues/160

**Comment by sandyasheri-gft** [comment]
Also Changed the URI  related to 'teammembers' end point to camel case
 (like : 'teamMembers', 'teamMember/{oid}')
