### ISSUE TITLE
[BUG] on PUT '/api/solution/{oid}' environments are not being removed

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#252]
**Describe the bug**
on PUT `/api/solution/{oid}` environments are not being removed

**To Reproduce**
1. Go to swagger UI
2. Use PUT `/api/solution/1` method with `{"environments":[1,2,3]}`
3. Use GET `/api/solution/1` the relationship is created
4. Use PUT `/api/solution/1` method with `{"environments":[1,3]}`
5. Use GET `/api/solution/1`, see the error, the relationship is not removed

**Expected behavior**
1. In **5.** the relationship between `solutionId=1` and `environmentId=2` should be set "isActive=false"
2. Do not return inactive relational data

**Screenshots**
N/A

**Additional context**
https://github.com/tranquilitybase-io/tb-houston-service/issues/231

**Comment by karwootang-gft** [comment]
Agreed the inactivation of the solution environment relationship is missing.
