### ISSUE TITLE
[BUG] "/api/activators/" Failing to return accessRequestedBy data

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#269]
**Describe the bug**
The API is not returning the user object as `accessRequestedBy`, just an empty object.
- e.g. GET `/api/activators/?category=Micro-services`

**To Reproduce**
1. Login using DEV user
1. Go to Activator Store
1. Select "Request Access" to any `Locked` Activator
1. Login using ADMIN user
1. Go to Activator Store
1. See error

**Expected behavior**
The API should return the User object as `accessRequestedBy` data

**Screenshots**

![image](https://user-images.githubusercontent.com/5604834/84841265-34d06e00-b018-11ea-8763-164cfa66af27.png)

**Additional context**
When a User requests access to an Activator the Admin User must Grant access. At this moment the Dialog Box shows User info.

**Comment by karwootang-gft** [comment]
Can we make a change to how accessRequestedBy modelled to be consistent with other objects?
I suggest that we rename the column on the DB to accessRequestedById.
The HS will the expand the activator and populate the acccessRequestedBy field with a user object.

This will make the code easier to write and maintain.

**Comment by stugit** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/272

**Comment by karwootang-gft** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/272
