### ISSUE TITLE
[Feature] Implement Notifications backend for Activators, database tables, and rest api endpoints to create and read notifications

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#280]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...\]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
@karwootang-gft is this implementation finished?

**Comment by karwootang-gft** [comment]
> @karwootang-gft is this implementation finished?

Yes, it's complete.

**Comment by Salles-FA** [comment]
Related issue:
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/199
