### ISSUE TITLE
/api/notifications/ - Add server-side pagination and sort

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#283]
**Is your feature request related to a problem? Please describe.**
Currently the `/api/notifications/` EndPoint is returning all notifications in a list. We are going to implement a lazyLoaded list in the UI (https://github.com/tranquilitybase-io/tb-eagle-console/issues/199). It requires some changes in the initial implementation of this new functionality.

**Describe the solution you'd like**
Implement new functionalities to allow "lazyLoaded" list in the UI.
-  Add server side pagination to `/api/notifications`
-  Add a new Metadata EndPoint with the count: `/api/notifications_meta`

**Describe alternatives you've considered**
N/A

**Additional context**
This feature has the potential to have a huge amount of items depending on the number of teams, users and available activators.

**Comment by karwootang-gft** [comment]
New section added to Confluence documentation - "Server side pagination and sorting examples (supported by POST and GET)" with examples.

https://confluence.gft.com/pages/viewpage.action?pageId=230601675
