### ISSUE TITLE
[BUG] You can deploy an Activator in a Solution that has not been deployed

### ISSUE THREAD

**Issue by andy12838729** [tranquilitybase-io/tb-houston-service#295]
**Describe the bug**
You are able to deploy an Activator in a solution that has not yet been deployed.

**To Reproduce**
Create a Solution, but do not deploy it. Add an Activator and deploy the Activator. This should not be possible.

**Expected behavior**
Either an Error message should be displayed or the user should be asked if they want to deploy the solution first. If use says yes, then queue the solution deployment and the Activator deployment with the DaC. 

This should also work from the "Deploy All" button. ie if there is a Solution that hasn't been deployed and _n_ Activators in the solution that also haven't been deployed, then queue all items with the DaC with the Solution creation as the first item in the queue.

**Screenshots**

**Additional context**

**Comment by karwootang-gft** [comment]
In the UI the Deploy button is greyed out, if the Solution has not been deployed.
In Houston, you get the following response:
![Screenshot 2020-07-28 at 10 06 43](https://user-images.githubusercontent.com/61692208/88643792-126f4d00-d0ba-11ea-8cb8-c65915e873ae.png)
