### ISSUE TITLE
Create workspace table

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#3]
Create workspace table and CRUD APIs.

Table definition:
-	WorkspaceID
-	CIService
-	CDService
-	SourceControlService

Add workspaceID to solution table

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/19

**Comment by karwootang-gft** [comment]
The solution table already contains the information regarding the workspace, the information tightly coupled with the solution so there's no need to move this information out of the solution table into it's own table.

e.g. ci, cd, sourceControl, environments.
