### ISSUE TITLE
[Feature] Notifications enhancements

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#308]
As discussed with Fabio and Kasia: 

- GET /api/notifications should return all types of notification, typeId is therefore optional.
- POST /api/setActivatorStatus should create notifications

**Comment by Salles-FA** [comment]
Related issues:
- https://github.com/tranquilitybase-io/tb-houston-service/issues/278
- https://github.com/tranquilitybase-io/tb-houston-service/issues/280
