### ISSUE TITLE
[Feature] Add createdBy as a parameter to Create Solution DAC call

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-houston-service#313]
Add createdBy as a parameter to Create Solution DAC call.
The value of createdBy should be the user that requested the solution to be created.
This value will be added as a label to projects created in the solution

**Comment by karwootang-gft** [comment]
Example test message sent:

solution_deployment: {
    "cd": "Screwdriver",
    "businessUnit": "Data",
    "createdBy": "Karwoo Tang",
    "isActive": true,
    "environments": [
        "Development",
        "Production",
        "test-env"
    ],
    "cdId": 2,
    "description": "test put",
    "ciId": 2,
    "ci": "Cloud native",
    "team": {
        "name": "Developers",
        "lastUpdated": "2020-03-01 12:34:56",
        "businessUnitId": 1,
        "isActive": true,
        "teamMembers": [
            {
                "id": 2,
                "isActive": true,
                "isTeamAdmin": false,
                "roleId": 1,
                "role": {
                    "description": "eagle console admin role",
                    "id": 1,
                    "name": "admin",
                    "cloudIdentityGroup": "ecadmins@gftdevgcp.com"
                },
                "teamId": 1,
                "userId": 1,
                "user": {
                    "isAdmin": false,
                    "firstName": "Jon",
                    "lastName": "Snow",
                    "email": "dev@your.company",
                    "isActive": true,
                    "showWelcome": true,
                    "id": 1,
                    "lastUpdated": "2020-03-01 12:34:56"
                }
            }
        ],
        "id": 1,
        "description": "All Developers",
        "businessUnit": {
            "description": "Modern Apps",
            "id": 1,
            "name": "Modern Apps",
            "isActive": true
        }
    },
    "isFavourite": false,
    "sourceControl": "Cloud native",
    "id": 149,
    "name": "test put",
    "deploymentFolderId": "MOCKFOLDERID3",
    "sourceControlId": 2,
    "lastUpdated": "2020-07-27 09:21:55",
    "costCentre": "test put",
    "teamId": 1
}
