### ISSUE TITLE
[Feature] For each environment store and use the gcp shared vpc project id

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-houston-service#336]
- [x] Each environment (prod, dev, etc) should have an associated shared vpc project id stored in the database.
- [x] For a standard installation this project id will be the same for each environment.

- [ ] The shared vpc project id will be obtained from dac in the initial metadata api call.

- [ ] Whenever an environment is sent to dac (deploy solution, deploy activator) its shared vpc project id should be sent along with its name. This will require equivalent changes in DAC.

**Comment by Salles-FA** [comment]
> For a standard installation this project id will be the same for each environment.

Done by:
- https://github.com/tranquilitybase-io/tb-db/issues/45
- https://github.com/tranquilitybase-io/tb-db/pull/54

![image](https://user-images.githubusercontent.com/5604834/88713865-541bea00-d0f2-11ea-8ed3-f81d32f912f7.png)

**Comment by Salles-FA** [comment]
> Each environment (prod, dev, etc) should have an associated shared vpc project id stored in the database.

Done by:
- https://github.com/tranquilitybase-io/tb-db/issues/47
- https://github.com/tranquilitybase-io/tb-db/pull/55

**Comment by karwootang-gft** [comment]
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/124

**Comment by karwootang-gft** [comment]
Example solution deployment:

`DEBUG:tb_houston_service.solution_deployment:send_solution_deployment_to_the_dac::solution_deployment: {
    "deploymentFolderId": "MOCKFOLDERID4",
    "ci": "Cloud native",
    "teamId": 3,
    "environments": [
        {
            "id": 1,
            "sharedVPCProjectId": "shared_vpc_host_project",
            "name": "Development"
        }
    ],
    "team": {
        "businessUnit": {
            "isActive": true,
            "id": 4,
            "name": "Finance",
            "description": "Finance"
        },
        "name": "Finance Team",
        "teamMembers": [
            {
                "id": 4,
                "isActive": true,
                "isTeamAdmin": false,
                "teamId": 3,
                "userId": 4,
                "user": {
                    "lastName": "Doe",
                    "showWelcome": true,
                    "isAdmin": false,
                    "isActive": true,
                    "lastUpdated": "2020-07-29 15:31:43",
                    "email": "john.doe@tranquilitybase-demo.io",
                    "id": 4,
                    "firstName": "John"
                }
            }
        ],
        "isActive": true,
        "lastUpdated": "2020-07-20 12:34:56",
        "id": 3,
        "businessUnitId": 4,
        "description": "Finance Team"
    },
    "name": "test2",
    "costCentre": "karwoo",
    "cd": "Screwdriver",
    "businessUnit": "Data",
    "isActive": true,
    "isFavourite": false,
    "sourceControl": "Cloud native",
    "lastUpdated": "2020-07-30 18:27:41",
    "cdId": 2,
    "ciId": 2,
    "sourceControlId": 2,
    "id": 13,
    "description": "test2"
}`

**Comment by karwootang-gft** [comment]
Example app deployment:

```
DEBUG:tb_houston_service.application_deployment:send_application_deployment_to_the_dac::application_deployment: {
    "mandatoryVariables": [],
    "description": "adfsdfds",
    "lastUpdated": "2020-07-30 18:44:59",
    "deploymentProjectId": "development-h08aez-ksjs726s",
    "deploymentEnvironment": {
        "id": 1,
        "sharedVPCProjectId": "shared_vpc_host_project",
        "name": "Development"
    },
    "name": "test3",
    "activatorGitUrl": "https://github.com/tranquilitybase-io/tb-activator-gft-base.git",
    "id": 12,
    "workspaceProjectId": "workspace-h08aez-ksjs726s",
    "optionalVariables": [],
    "solutionId": 13
}
```

**Comment by karwootang-gft** [comment]
A pending PR created for early review: 
https://github.com/tranquilitybase-io/tb-houston-service/pull/354
