### ISSUE TITLE
[BUG] Activator request access by dev user feature not working

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-houston-service#339]
- Dev user is calling POST 'api/setactivatorstatus' passing through the 'accessRequestedById' value.
- POST method returns the JSON correctly (with accessRequestedBy filled in with the user information)
- GET 'api/activators' list items is not returning 'accessRequestedBy' object.

**Comment by sandyasheri-gft** [comment]
@Salles-FA ,  It is working in master after all merges.

Please test again and let me know if it still an issue.


{
  "accessRequestedBy": {
    "email": "dev@your.company",
    "firstName": "Jon",
    "id": 1,
    "isActive": true,
    "isAdmin": false,
    "lastName": "Snow",
    "lastUpdated": "2020-03-01 12:34:56",
    "showWelcome": true
  },
  "accessRequestedById": 1,
  "activator": "SQL Single region kubernetes",
  "activatorLink": "",
  "apiManagement": [
    "ApiGee"
  ],
  "available": true,
  "billing": "Monthly: Eagle tier 2",
  "businessUnit": "Equity Capital Business Unit",
  "category": "Micro-services",
  "cd": [
    "Codeship",
    "Option"
  ],
  "ci": [

**Comment by Salles-FA** [comment]
Looks good, thx @sandyasheri-gft
