### ISSUE TITLE
[Feature] API changes to read and publish Activator Metadata from a yml file

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-houston-service#364]
**Is your feature request related to a problem? Please describe.**
We need to read activator_metadata.yml from https://github.com/tranquilitybase-io/tb-activator-gft-base/tree/master/.tb and 
save activator and activatorMetadata details from it.

**Describe the solution you'd like**
1. We read yml from using github API. We have agreed to read it from public repo for the time being.
2. We read fields required and send to existing 'activator' API to post a new activator. Which creates the basic activator and returns 'activatorId'
3. Now we create a 'ActivatorMetadata' record and refer above 'activatorId'. This creates an 'activatorMetadata' record and return 'activatorMetadataId'
5. Insert entries into 'activatorMetadataPlatform' table to handle many-many relationship .
4. We now create  many 'ActivatorMetadataVariables' record and map above 'activatorMetadataId'. 
5. Make sure all the above DB inserts are part of single transaction.

**Describe alternatives you've considered**

**Additional context**

**Comment by sandyasheri-gft** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/365

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/47
