### ISSUE TITLE
[Feature] Pass 'created by' when deploying a solution or an activator

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-houston-service#375]
When deploying a solution or an activator, need to know what user requested the deployment. Use the field name 'createdBy'. The field value should be the name or user name of the person who started the deployment via the Eagle Console i.e. whoever is logged in.

**Comment by karwootang-gft** [comment]
Couple of things that this issue is blocked by:
1. DaC Application/Activator deployment doesn't support createdBy field yet. 
2. EC needs to send the Authorisation Bearer token to the Solution/Application deployment endpoints.

**Comment by sunderhill-gft** [comment]
1. is not a blocker. It can be added to the deploy activator call
