### ISSUE TITLE
[Feature]   Activator onboarding Step 1: Return full activator (+ embedded activatorMetadata object) when using the activatorByURL endpoint

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#378]
**Is your feature request related to a problem? Please describe.**
Currently post endpoint is only returning the activatorMetadata object 

**Describe the solution you'd like**
Instead it needs to return the activator object with the activator metadata object embedded within it.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/47
