### ISSUE TITLE
[Feature] Activator onboarding Step 2 + 3: Activator PUT method will process and update embedded  activator metadata object

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#379]
**Is your feature request related to a problem? Please describe.**
Activator PUT method needs to change to also allow the processing and updating of the embedded activator metadata object.

**Describe the solution you'd like**

e.g. 

{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": null,
  "activatorMetadata": {
    "activatorLink": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
    "category": "Infrastructure",
    "description": "A helloworld example of an activator.",
    "id": 12,
    "lastUpdated": "2020-09-15 13:57:59",
    "name": "Tranquility Base GFT Base",
    "platforms": [
      {
        "id": 1,
        "value": "GCP"
      }
    ],
    "type": {
      "id": 3,
      "value": "Tier 3"
    },
    "typeId": 3,
    "variables": [
      {
        "activatorMetadataId": 12,
        "id": 1,
        "isOptional": false,
        "name": "standard_subnetwork",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "id": 2,
        "isOptional": false,
        "name": "zone",
        "type": "tb_zone",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "id": 3,
        "isOptional": false,
        "name": "host_project_id",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "id": 4,
        "isOptional": false,
        "name": "region",
        "type": "tb_region",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "id": 5,
        "isOptional": true,
        "name": "vms_size",
        "type": "tb_vms_size",
        "value": ""
      }
    ]
  },
  "apiManagement": null,
  "available": null,
  "billing": null,
  "businessUnit": null,
  "businessUnitId": null,
  "cd": [],
  "ci": [],
  "envs": [],
  "gitRepoUrl": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
  "hosting": null,
  "id": 12,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-09-15 13:57:59",
  "name": "Tranquility Base GFT Base",
  "regions": null,
  "sensitivity": null,
  "serverCapacity": null,
  "source": null,
  "sourceControl": null,
  "sourceControlId": null,
  "status": "Draft",
  "technologyOwner": null,
  "technologyOwnerEmail": null,
  "userCapacity": null
}

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/47
