### ISSUE TITLE
Read activator metadata file from a private github repo using credentials[Feature]

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-houston-service#382]
**Is your feature request related to a problem? Please describe.**
Currently reading activator metadata yaml file from a public git hub repo. 
Change is to read the file from a private repo by using credentials to authenticate.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andy12838729** [comment]
Will we be able to support both public and private repos with this change ?

**Comment by Salles-FA** [comment]
Yes, this is the idea
