### ISSUE TITLE
Create teams table

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#4]
Create teams table and CRUD APIs.

Table definition:
-	Name #name of the team
-	Description
-	Users[] #list of users

See - https://github.com/tranquilitybase-io/tb-houston-service/wiki/Teams

**Comment by andy12838729** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/wiki/Teams

**Comment by Salles-FA** [comment]
Related issues:

1. Should be able to allow multiple teams to access activator. https://github.com/tranquilitybase-io/tb-eagle-console/issues/77
1. Set a budget for an Application. https://github.com/tranquilitybase-io/tb-eagle-console/issues/67
1. Should be able to view which Teams have permission to a Solution. https://github.com/tranquilitybase-io/tb-eagle-console/issues/63

**Comment by andy12838729** [comment]
Have added the requirement to have an email address (this is an SMTP group email address). This is because GCP requires for assigning a Project Owner.

**Comment by Salles-FA** [comment]
#171

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/23
