### ISSUE TITLE
update repository onboard payload call [Feature]

### ISSUE THREAD

**Issue by aivogft** [tranquilitybase-io/tb-houston-service#426]
**What kind of change does this refactoring issue introduce?**
- [x] Clean Code
- [ ] S.O.L.I.D. principles
- [ ] Performance improvement
- [ ] Complexity reduction
- [x] Maintainability improvement
- [ ] “Triangular” Code to Flat Code
- [ ] Other... Please describe:

**Is your refactoring request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...\]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/47

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/187

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/66
