### ISSUE TITLE
[Feature] "api/applicationDeployment" to send CSR url value from gitSnapshotJson

### ISSUE THREAD

**Issue by geoff-gft** [tranquilitybase-io/tb-houston-service#428]
**Is your feature request related to a problem? Please describe.**
Currently when the UI is calling "api/applicationDeployment/" POST method passing through the application primary-key as id, the API is retrieving the "gitRepoUrl" which is an external repo url (GitHub), and next sending it to DaC micro-service in order to start a jenkins job to effectively "Deploy" the application into a predefined solution.

Recently this flow has been changed during the onboarding process to have an "internal" (Cloud Source Repository) copy of the external repo under the "shared-ec-XXXXX" project. A new column has been created in the database to store all options available to be used in order to clone this CSR repo "gitSnapshotJson".

- https://github.com/tranquilitybase-io/tb-gcp-dac/issues/109
- https://github.com/tranquilitybase-io/tb-houston-service/issues/415
- https://github.com/tranquilitybase-io/tb-db/issues/85

**Describe the solution you'd like**
DaC micro-service is expecting a CSR url with the following format:
- url_prefix + "p/" + project_id + "/r/" + local_repo
  - e.g.: `https://source.developers.google.com/p/shared-ec-yzw0s/r/test`

1. Change the following line to receive the CSR url created previously during the onboarding process.
 https://github.com/tranquilitybase-io/tb-houston-service/blob/3a1696c7f4ac8f3a7c68fea2d5b1eb10f24b69f8/tb_houston_service/application_deployment.py#L244 

**Describe alternatives you've considered**
N/A

**Additional context**
- https://github.com/tranquilitybase-io/TranquilityBase/issues/47

**Comment by RDHA-GFT** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/65
