### ISSUE TITLE
Create users table

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#5]
Create users table and CRUD APIs.

Table definition:
-	Name
-	UserID
-	email

**Comment by karwootang-gft** [comment]
Discussed this with Fabio, and what they need right now is id, username, firstname, lastname and isAdmin. Also, added user object to Solution and activator endpoints.

**Comment by karwootang-gft** [comment]
We can now update userId field from setactivatestatus endpoint.
