### ISSUE TITLE
Retrieve list of Activators

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#8]
Retrieve list of Activators:
o	All
o	By Category
o	By Status  (Available, Locked, Deprecated)
o	By Environment (Defined by the Dac.getEnvironments() function
o	By Cloud platform
o	By Type (Tier 0, 1, 2 3 etc) #UI has called this category by mistak
o	By Source (Open, thirdparty, internal)
o	By Datasensitivity (public, restricted)

**Comment by karwootang-gft** [comment]
@oscarmon7 , @Salles-FA, @sunderhill-gft  - Is activator.source column the same as the sourceControl column? If not we're missing a column.

Will use sourceControl column for now, and raise a new ticket to  resolve  any issue.

thanks,
Karwoo

**Comment by andy12838729** [comment]
Hi - they are different.  SourceControl would be the system like git or if on GCP - Cloud Source Repositories that the Activator can be deployed to. (Configured in EC).

There also needs to be a link to the actual code for the activator.

**Comment by karwootang-gft** [comment]
@andy12838729 - thanks I will add a task for that
