### ISSUE TITLE
Add semantic versioning to the tb-houston-service repo

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-houston-service#82]
See documentation on https://semver.org/

e.g.

cat version.json
{ "version": { "major": 0, "minor": 1, "patch": 0 } }

Essentially:

A Push or Pull Request from a branch called:
patch/* or hotfix/* will cause the patch number to increment by 1

A Push or Pull Request from a branch called:
feature/* will cause the minor number to increment by 1 and the patch number to reset to zero.

A Push or Pull Request from a branch called:
major/* will cause the major number to increment by 1 and the minor and patch number to reset to zero.

The version.json file is added to the Push/PR, and maintained in Source Control.
The semantic version number will be used for all image creation as the tag so that it can be referred back to the original code that created the image.

The docker-compose yaml files should refer to a specific version as opposed to a statically named image. 

e.g.

services:
  mysql57:
    image: gcr.io/tranquility-base-images/tb-houston-mysql57:v0.1.2
...
  houston-service:
    image: gcr.io/tranquility-base-images/tb-houston-service:v0.1.2

**Comment by Salles-FA** [comment]
We need a versioning scheme capable of making it very clear which versions are being tested by the development team and which versions are available to update the 'docker-compose.yml' files. 
**For example**:
	1. 0.2-a1 (alpha version, development and test purposes)
	1. 0.2-b2 (beta with some bug fixes)
	1. 0.2-rc3 (release candidate)
	1. 0.2-r (commercial distribution)
	1. 0.2-r5 (commercial distribution with many bug fixes)

In addition, we need to define something that is adopted as the current version for both repositories, tb-huston-service and tb-eagle-console. To keep track of changes and to became useful to rollback in case of bugs.
**For example**:
- gcr.io/tranquility-base-images/tb-houston-mysql57:v0.1.2rc
- gcr.io/tranquility-base-images/tb-houston-service:v0.1.2rc
- gcr.io/tranquility-base-images/tb-eagle-console:v0.1.2rc
