### ISSUE TITLE
Retrieve list of environments

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-houston-service#9]
Retrieve list of environments:
- getEnvironments() – calls the DaC.get… to retrieve a list of the allowed environments (Dev, Test, UAT, Sandbox, Prod)

LInked issue - https://github.com/tranquilitybase-io/tb-eagle-console/issues/66

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/17
https://github.com/tranquilitybase-io/TranquilityBase/issues/24

**Comment by karwootang-gft** [comment]
@sunderhill-gft, @Salles-FA - do know if the DAC have plans to have an API to retrieve a list of allowed environments?

In the HS we have an table called "environment" containing 2 rows (it's manually maintained at the moment):

KEY, Value
'Development','Development'
'Production','Production'

**Comment by sunderhill-gft** [comment]
The DAC doesn't decide what possible environments there are. There will be a list of pre-defined environments - Dev, Staging, QA., Prod etc. The Eagle Console admin will also be able to add custom environments too.
The pre-defined environments should probably be pre-loaded as metadata into the houston database when Eagle first starts up.

**Comment by karwootang-gft** [comment]
@Salles-FA are you happy to close this issue, will create a new issue for better management of the database, which will include the loading of reference data.

**Comment by Salles-FA** [comment]
Hi @karwootang-gft, 

Ok!

This table you mentioned is about to change. These are the EC issue to allow the User add custom environments: 

- https://github.com/tranquilitybase-io/tb-eagle-console/issues/71
- https://github.com/tranquilitybase-io/tb-eagle-console/issues/66

**Comment by karwootang-gft** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/17 - this issue that's in review covers this.
